version: "3"

services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5432
    network_mode: host
    command: [ "postgres", "-c", "log_statement=all" ]
