version: "3"
services:

  nginx:
    image: nginx
    network_mode: host
    environment:
      PORT: 5002
    volumes:
      - "./etc_nginx/:/etc/nginx/" # config
      - "../fe_hwp/dist/:/usr/share/nginx/html" # build
    command:
      [
        "/bin/sh",
        "-c",
        "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
      ]
